services:
  user-11-mvc: &user-11
    build:
      context: ./
      dockerfile: user-11-mvc/Dockerfile
    hostname: user-11-mvc
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/app
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_MAX_POOL_SIZE=20
      - SPRING_JPA_SHOW_SQL=false
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'

  user-11-webflux:
    <<: *user-11
    build:
      context: ./
      dockerfile: user-11-webflux/Dockerfile
    hostname: user-11-webflux

  user-11-webflux-coroutines:
    <<: *user-11
    build:
      context: ./
      dockerfile: user-11-webflux-coroutines/Dockerfile
    hostname: user-11-webflux-coroutines

  db:
    image: postgres:16.2-alpine
    hostname: db
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U admin -d app'" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.2GB'

networks:
  default:
    name: app-network
    driver: bridge